### PR TITLE
Ports #14987 from /tg/station [WIP]

### PR DESCRIPTION
**Pull request by Wilchenx**
Original PR https://github.com/tgstation/tgstation/pull/14987

image

image
sprites by Chocobro.

```changelog
(u)Francinum, Wilchen
(+)Added two new female underwear styles.
```

### CODE REVIEW

**Comment by bluezorua** [comment]
add chocobro to the changelog i guess since they made the sprite

**Comment by MCterra10** [comment]
weren't you the guy who got banned for erping with a prisoner on /tg/?

**Comment by Wilchenx** [comment]
> weren't you the guy who got banned for erping with a prisoner on /tg/?

No I won't erp with you stop asking me, creep.

**Comment by MCterra10** [comment]
> 
> 
> > weren't you the guy who got banned for erping with a prisoner on /tg/?
> 
> No I won't erp with you stop asking me, creep.

bit of salt eh

**Comment by Wilchenx** [comment]
I have tested this but the option doesn't show in preferences.

**Comment by ike709** [comment]
Ignoring the actual content of this PR, the asset license is not the same and we need a folder for CC-BY-SA assets.

**Comment by francinum** [comment]
Changelog format is incorrect.

**Comment by Wilchenx** [comment]
I got the creator of the sprite to allow them being used under new license, the option now correctly shows up in dropmenu.

I've still yet to test this ingame.

**Pull request closed without merging**
